builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

# No archives
archives:
 - format: binary

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  skip: true
